### ISSUE TITLE
Wrong focus cycle when moving back

### ISSUE THREAD

**Issue by tilonorrinco** [theKashey/dom-focus-lock#8]
Hello! I faced with strange behavior when moving focus on page with lack of focusable elements.
I made a sandbox here: 
https://zt0kk.csb.app/ 
Just try to move focus with shift + tab. Focus moves from button#1 to browser interface and then I can't focus button#2 
Here is short video. Firstly I move focus forward and after it -- back.

https://user-images.githubusercontent.com/25035421/145574617-91141e4d-a4f5-4c9a-8666-4504064031e7.mp4

I use Chrome 96.0.4664.93

**Comment by theKashey** [comment]
Hey, this is a known limitation, solved by other `focus-lock` implementations, but the one this one cannot handle.

## How its solved by others
react/vue locks uses 'focus-guards' - invisible elements before and after the lock to "trap" focus and let the lock do the job. Basically, there will be always something to focus before and something to focus after.
A little tricky thing is to keep those guards active only around the current lock

## Why this library cannot do the same
Because "dom" focuslock is not responsible for markup and cannot add these extra elements.

## Solution
manually add those nodes, but 😭 only when the lock is active
https://codesandbox.io/s/great-feather-wkinj?file=/index.html
